[package]
name = "new_button_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
axum = "0.7.5"
chrono = "0.4.38"
rppal = "0.17.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs"] }

[profile.release]
lto = true
strip = true
