# content of .cargo/config
[build]
target = ["arm-unknown-linux-gnueabihf"]

# for raspberry pi 1/zero
# get from https://github.com/abhiTronix/raspberry-pi-cross-compilers#-toolchain-downloads
[target.arm-unknown-linux-gnueabihf]
linker = "/home/lroesel/.toolchains/cross-pi-gcc-10.3.0-0/bin/arm-linux-gnueabihf-gcc"
rustflags = [
    "-C", "link-arg=--sysroot=/home/lroesel/.toolchains/cross-pi-gcc-10.3.0-0/arm-linux-gnueabihf/libc"
]


# for the raspberry pi 3/4 or (Zero W 2) use/uncomment the following:
# [build]
# target = ["arm-unknown-linux-gnueabihf"]

# #for raspberry pi 3/4
# [target.aarch64-unknown-linux-gnu]
# linker = "/home/judge/.toolchains/cross-pi-gcc-10.3.0-64/bin/aarch64-linux-gnu-gcc"
# rustflags = [
#     "-C", "link-arg=--sysroot=/home/judge/.toolchains/cross-pi-gcc-10.3.0-0/aarch64-linux-gnu/libc"
# ]